### ISSUE TITLE
Error with bsc-flags, NPM version needs to be bumped

### ISSUE THREAD

**Issue by liamcurry** [yamadayuki/bs-url#1]
Using this package from NPM is throwing errors related to `bsc-flags`. Looks like those were fixed in this commit https://github.com/yamadayuki/bs-url/commit/f49d11e7e5528f3e1a753594e9b56714913c7839#diff-f41ca12831738be5112886ab27935569L18

But the NPM version is still outdated and doesn't include this fix. Bumping the version to `0.1.1` and republishing should fix the issue.

In the meantime I installed the Github version with `yarn add yamadayuki/bs-url`

**Comment by yamadayuki** [comment]
Sorry to reply you so late and thank you. I had fixed this issue and the version is bumped. So you can try once more. `yarn add @yamadayuki/bs-url`

**Comment by liamcurry** [comment]
No worries. I'm not able to confirm this is fixed right now but if you say it's working then feel free to close this issue. Thanks!

**Comment by yamadayuki** [comment]
Tons of thanks!
